var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/trpc/[trpc]/route.js")
R.c("server/chunks/node_modules_next_dist_4ea737b1._.js")
R.c("server/chunks/node_modules_@opentelemetry_api_build_esm_7e8f41ca._.js")
R.c("server/chunks/node_modules_@trpc_server_dist_bdbf1e8b._.js")
R.c("server/chunks/node_modules_zod_v4_e9fec30e._.js")
R.c("server/chunks/node_modules_@anthropic-ai_sdk_3c95f3a1._.js")
R.c("server/chunks/node_modules_openai_f417a314._.js")
R.c("server/chunks/node_modules_fbaf0329._.js")
R.c("server/chunks/[root-of-the-server]__0428d25d._.js")
R.c("server/chunks/_next-internal_server_app_api_trpc_[trpc]_route_actions_646e8836.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/trpc/[trpc]/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/trpc/[trpc]/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
