;!function(){try { var e="undefined"!=typeof globalThis?globalThis:"undefined"!=typeof global?global:"undefined"!=typeof window?window:"undefined"!=typeof self?self:{},n=(new e.Error).stack;n&&((e._debugIds|| (e._debugIds={}))[n]="1a164d46-a639-9785-5507-8c4abf1ef11b")}catch(e){}}();
module.exports = [
"[project]/src/app/favicon.ico.mjs { IMAGE => \"[project]/src/app/favicon.ico (static in ecmascript, tag client)\" } [app-rsc] (structured image object, ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/src/app/favicon.ico.mjs { IMAGE => \"[project]/src/app/favicon.ico (static in ecmascript, tag client)\" } [app-rsc] (structured image object, ecmascript)"));
}),
"[externals]/next/dist/shared/lib/no-fallback-error.external.js [external] (next/dist/shared/lib/no-fallback-error.external.js, cjs)", ((__turbopack_context__, module, exports) => {

const mod = __turbopack_context__.x("next/dist/shared/lib/no-fallback-error.external.js", () => require("next/dist/shared/lib/no-fallback-error.external.js"));

module.exports = mod;
}),
"[project]/src/app/global-error.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/src/app/global-error.tsx [app-rsc] (ecmascript)"));
}),
"[project]/src/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/src/app/layout.tsx [app-rsc] (ecmascript)"));
}),
"[project]/src/components/dashboard/dashboard-shell.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "DashboardShell",
    ()=>DashboardShell,
    "default",
    ()=>__TURBOPACK__default__export__
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const DashboardShell = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call DashboardShell() from the server but DashboardShell is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/components/dashboard/dashboard-shell.tsx <module evaluation>", "DashboardShell");
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/src/components/dashboard/dashboard-shell.tsx <module evaluation> from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/components/dashboard/dashboard-shell.tsx <module evaluation>", "default");
}),
"[project]/src/components/dashboard/dashboard-shell.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "DashboardShell",
    ()=>DashboardShell,
    "default",
    ()=>__TURBOPACK__default__export__
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const DashboardShell = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call DashboardShell() from the server but DashboardShell is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/components/dashboard/dashboard-shell.tsx", "DashboardShell");
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/src/components/dashboard/dashboard-shell.tsx from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/components/dashboard/dashboard-shell.tsx", "default");
}),
"[project]/src/components/dashboard/dashboard-shell.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$dashboard$2f$dashboard$2d$shell$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/src/components/dashboard/dashboard-shell.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$dashboard$2f$dashboard$2d$shell$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/src/components/dashboard/dashboard-shell.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$dashboard$2f$dashboard$2d$shell$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/src/components/dashboard/data.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

// src/components/dashboard/data.ts
__turbopack_context__.s([
    "analytics",
    ()=>analytics,
    "primaryNav",
    ()=>primaryNav,
    "reviewChecklist",
    ()=>reviewChecklist,
    "secondaryNav",
    ()=>secondaryNav,
    "statCards",
    ()=>statCards,
    "timeline",
    ()=>timeline,
    "transactions",
    ()=>transactions
]);
const primaryNav = [
    {
        label: "Dashboard",
        key: "dashboard",
        active: true
    },
    {
        label: "Perfil",
        key: "profile",
        active: false
    },
    {
        label: "Perguntas",
        key: "questions",
        active: false
    },
    {
        label: "Experiencias",
        key: "experiences",
        active: false
    },
    {
        label: "Competencias",
        key: "skills",
        active: false
    },
    {
        label: "Speech",
        key: "speech",
        active: false
    },
    {
        label: "Analytics",
        key: "analytics",
        active: false
    }
];
const secondaryNav = [
    {
        label: "Configuracoes",
        key: "settings"
    },
    {
        label: "Suporte",
        key: "support"
    },
    {
        label: "Sair",
        key: "logout"
    }
];
const statCards = [
    {
        label: "Mock interviews",
        amount: "12 sessoes",
        change: "+11.94%",
        trend: "positive",
        path: "M4 52L32 44L60 58L88 38L116 46L144 30L172 56L200 34L228 40L256 30L284 42L312 28",
        gradientId: "balanceGradient",
        gradientStops: [
            {
                offset: "0%",
                color: "rgba(154, 193, 240, 0.5)"
            },
            {
                offset: "100%",
                color: "rgba(114, 250, 147, 0.2)"
            }
        ]
    },
    {
        label: "Perguntas respondidas",
        amount: "148 respostas",
        change: "+8.20%",
        trend: "positive",
        path: "M4 60L32 48L60 56L88 30L116 38L144 26L172 34L200 22L228 42L256 26L284 32L312 18",
        gradientId: "responseGradient",
        gradientStops: [
            {
                offset: "0%",
                color: "rgba(114, 250, 147, 0.55)"
            },
            {
                offset: "100%",
                color: "rgba(160, 229, 72, 0.25)"
            }
        ]
    },
    {
        label: "Feedbacks coach",
        amount: "5 novos",
        change: "-2.10%",
        trend: "negative",
        path: "M4 40L32 44L60 30L88 46L116 34L144 50L172 36L200 48L228 28L256 38L284 24L312 30",
        gradientId: "feedbackGradient",
        gradientStops: [
            {
                offset: "0%",
                color: "rgba(228, 95, 43, 0.5)"
            },
            {
                offset: "100%",
                color: "rgba(154, 193, 240, 0.2)"
            }
        ]
    }
];
const reviewChecklist = [
    {
        title: "Mock interview agendado",
        type: "voice"
    },
    {
        title: "Rever perguntas comportamentais",
        type: "todo"
    },
    {
        title: "Atualizar portfolio",
        type: "todo"
    },
    {
        title: "Treinar pitch de apresentacao",
        type: "voice"
    }
];
const transactions = [
    {
        name: "Mock interview com mentor",
        date: "27 Jul 2025",
        amount: "-$199.00"
    },
    {
        name: "Aula intensiva de casos",
        date: "26 Jul 2025",
        amount: "-$149.00"
    },
    {
        name: "Reembolso evento tech",
        date: "20 Jul 2025",
        amount: "+$89.00"
    },
    {
        name: "Mensalidade Interview Prep",
        date: "15 Jul 2025",
        amount: "-$39.00"
    }
];
const analytics = [
    {
        label: "Apresentacao",
        value: 86,
        color: "bg-brand-green"
    },
    {
        label: "Tecnico",
        value: 72,
        color: "bg-brand-blue"
    },
    {
        label: "Comportamental",
        value: 64,
        color: "bg-brand-orange"
    },
    {
        label: "Cultura da empresa",
        value: 58,
        color: "bg-brand-yellow"
    },
    {
        label: "Perguntas invertidas",
        value: 44,
        color: "bg-brand-lime"
    }
];
const timeline = [
    {
        label: "Pitch pessoal",
        value: 92,
        tone: "positive"
    },
    {
        label: "Projetos recentes",
        value: 76,
        tone: "positive"
    },
    {
        label: "Framework STAR",
        value: 63,
        tone: "positive"
    },
    {
        label: "Feedbacks anteriores",
        value: 41,
        tone: "warning"
    }
];
}),
"[project]/src/components/dashboard/index.ts [app-rsc] (ecmascript) <locals>", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([]);
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$dashboard$2f$dashboard$2d$shell$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/components/dashboard/dashboard-shell.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$dashboard$2f$data$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/components/dashboard/data.ts [app-rsc] (ecmascript)");
;
;
}),
"[project]/src/app/design-test/page.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>DesignTest
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$dashboard$2f$index$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$locals$3e$__ = __turbopack_context__.i("[project]/src/components/dashboard/index.ts [app-rsc] (ecmascript) <locals>");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$dashboard$2f$dashboard$2d$shell$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/components/dashboard/dashboard-shell.tsx [app-rsc] (ecmascript)");
;
;
function DesignTest() {
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$dashboard$2f$dashboard$2d$shell$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["DashboardShell"], {}, void 0, false, {
        fileName: "[project]/src/app/design-test/page.tsx",
        lineNumber: 4,
        columnNumber: 10
    }, this);
}
}),
"[project]/src/app/design-test/page.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/src/app/design-test/page.tsx [app-rsc] (ecmascript)"));
}),
];

//# debugId=1a164d46-a639-9785-5507-8c4abf1ef11b
//# sourceMappingURL=%5Broot-of-the-server%5D__49b3a4c9._.js.map