var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/design-test/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__46c6cf7e._.js")
R.c("server/chunks/ssr/_a3b9117b._.js")
R.c("server/chunks/ssr/_aa85ba15._.js")
R.c("server/chunks/ssr/[root-of-the-server]__fc039a51._.js")
R.c("server/chunks/ssr/node_modules_next_dist_8df46922._.js")
R.c("server/chunks/ssr/node_modules_0ecec565._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/src_app_global-error_tsx_aa661ba4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0918a202._.js")
R.c("server/chunks/ssr/_5b825777._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_2fffaa3a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_design-test_page_actions_43f177ae.js")
R.m(32128)
module.exports=R.m(32128).exports
