var R=require("./chunks/[turbopack]_runtime.js")("server/instrumentation.js")
R.c("server/chunks/[root-of-the-server]__dfdfd519._.js")
R.c("server/chunks/node_modules_@sentry_core_build_cjs_3c39bf7d._.js")
R.c("server/chunks/node_modules_@opentelemetry_api_build_esm_e96249e4._.js")
R.c("server/chunks/node_modules_@opentelemetry_82d18e1d._.js")
R.c("server/chunks/node_modules_@opentelemetry_semantic-conventions_build_esm_2ce702d6._.js")
R.c("server/chunks/node_modules_0a45dba2._.js")
R.c("server/chunks/node_modules_@sentry_node-core_build_cjs_f946a284._.js")
R.c("server/chunks/node_modules_@apm-js-collab_code-transformer_pkg_orchestrion_js_73ebd7cd.js")
R.c("server/chunks/node_modules_@apm-js-collab_code-transformer_index_87720b9d.js")
R.c("server/chunks/node_modules_@sentry_node_build_cjs_c5fbeedd._.js")
R.c("server/chunks/node_modules_@sentry_nextjs_build_cjs_11cd41e6._.js")
R.c("server/chunks/node_modules_05cf22b9._.js")
R.c("server/chunks/[root-of-the-server]__85effaa9._.js")
R.m("[project]/src/instrumentation.ts [instrumentation] (ecmascript)")
module.exports=R.m("[project]/src/instrumentation.ts [instrumentation] (ecmascript)").exports
